name = "EDtunnel"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "7b7cd655-8c33-4cfb-a77f-e3f4e0bada55"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
